WebApplication1/WebApplication1/Models/Cars.cs
using System.ComponentModel.DataAnnotations;

namespace CarRental.Models
{
    public class Cars
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Model { get; set; }

        public int An { get; set; }

        public string Firma { get; set; }

        public string Imagine { get; set; }

        public int HorsePower { get; set; }

        public string Traction { get; set; }

        public string Transmission { get; set; }

        public string FuelType { get; set; }

        public int Weight { get; set; }



    }
}

WebApplication1/WebApplication1/Controllers/CarsController.cs
using CarRental.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;

namespace WebApplication1.Controllers
{
    public class CarsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CarsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Cars


        public async Task<IActionResult> Index()
        {
            return _context.Cars != null ?
                        View(await _context.Cars.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Cars'  is null.");
        }

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cars == null)
            {
                return NotFound();
            }

            var cars = await _context.Cars
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cars == null)
            {
                return NotFound();
            }

            return View(cars);
        }

        // GET: Cars/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Model,An,Firma,Imagine,HorsePower,Traction,Transmission,FuelType,Weight")] Cars cars)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cars);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cars);
        }

        // GET: Cars/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cars == null)
            {
                return NotFound();
            }

            var cars = await _context.Cars.FindAsync(id);
            if (cars == null)
            {
                return NotFound();
            }
            return View(cars);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Model,An,Firma,Imagine,HorsePower,Traction,Transmission,FuelType,Weight")] Cars cars)
        {
            if (id != cars.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cars);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarsExists(cars.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cars);
        }

        // GET: Cars/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cars == null)
            {
                return NotFound();
            }

            var cars = await _context.Cars
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cars == null)
            {
                return NotFound();
            }

            return View(cars);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cars == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Cars'  is null.");
            }
            var cars = await _context.Cars.FindAsync(id);
            if (cars != null)
            {
                _context.Cars.Remove(cars);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarsExists(int id)
        {
            return (_context.Cars?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplication1/WebApplication1/Controllers/RentsController.cs
using CarRental.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;

namespace WebApplication1.Controllers
{
    public class RentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Rents
        public async Task<IActionResult> Index()
        {
            return _context.Rents != null ?
                        View(await _context.Rents.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Rents'  is null.");
        }

        // GET: Rents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Rents == null)
            {
                return NotFound();
            }

            var rents = await _context.Rents
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rents == null)
            {
                return NotFound();
            }

            return View(rents);
        }

        // GET: Rents/Create
        [Authorize(Roles = "Admin,Client")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Client")]
        public async Task<IActionResult> Create([Bind("Id,RentBegin,RentEnd,PayMethod")] Rents rents)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rents);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(rents);
        }

        // GET: Rents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Rents == null)
            {
                return NotFound();
            }

            var rents = await _context.Rents.FindAsync(id);
            if (rents == null)
            {
                return NotFound();
            }
            return View(rents);
        }

        // POST: Rents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,RentBegin,RentEnd,PayMethod")] Rents rents)
        {
            if (id != rents.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rents);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RentsExists(rents.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rents);
        }

        // GET: Rents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Rents == null)
            {
                return NotFound();
            }

            var rents = await _context.Rents
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rents == null)
            {
                return NotFound();
            }

            return View(rents);
        }

        // POST: Rents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Rents == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Rents'  is null.");
            }
            var rents = await _context.Rents.FindAsync(id);
            if (rents != null)
            {
                _context.Rents.Remove(rents);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RentsExists(int id)
        {
            return (_context.Rents?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplication1/WebApplication1/Views/Cars/Create.cshtml
@model CarRental.Models.Cars

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cars</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="An" class="control-label"></label>
                <input asp-for="An" class="form-control" />
                <span asp-validation-for="An" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Firma" class="control-label"></label>
                <input asp-for="Firma" class="form-control" />
                <span asp-validation-for="Firma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagine" class="control-label"></label>
                <input asp-for="Imagine" class="form-control" />
                <span asp-validation-for="Imagine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HorsePower" class="control-label"></label>
                <input asp-for="HorsePower" class="form-control" />
                <span asp-validation-for="HorsePower" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Traction" class="control-label"></label>
                <input asp-for="Traction" class="form-control" />
                <span asp-validation-for="Traction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Transmission" class="control-label"></label>
                <input asp-for="Transmission" class="form-control" />
                <span asp-validation-for="Transmission" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FuelType" class="control-label"></label>
                <input asp-for="FuelType" class="form-control" />
                <span asp-validation-for="FuelType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/WebApplication1/Views/Cars/Delete.cshtml
@model CarRental.Models.Cars

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cars</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.An)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.An)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Firma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Firma)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagine)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HorsePower)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HorsePower)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Traction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Traction)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Transmission)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Transmission)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FuelType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FuelType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication1/WebApplication1/Views/Cars/Details.cshtml
@model CarRental.Models.Cars

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cars</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.An)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.An)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Firma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Firma)
        </dd>
       
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HorsePower)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HorsePower)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Traction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Traction)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Transmission)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Transmission)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FuelType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FuelType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication1/WebApplication1/Views/Cars/Edit.cshtml
@model CarRental.Models.Cars

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cars</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="An" class="control-label"></label>
                <input asp-for="An" class="form-control" />
                <span asp-validation-for="An" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Firma" class="control-label"></label>
                <input asp-for="Firma" class="form-control" />
                <span asp-validation-for="Firma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagine" class="control-label"></label>
                <input asp-for="Imagine" class="form-control" />
                <span asp-validation-for="Imagine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HorsePower" class="control-label"></label>
                <input asp-for="HorsePower" class="form-control" />
                <span asp-validation-for="HorsePower" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Traction" class="control-label"></label>
                <input asp-for="Traction" class="form-control" />
                <span asp-validation-for="Traction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Transmission" class="control-label"></label>
                <input asp-for="Transmission" class="form-control" />
                <span asp-validation-for="Transmission" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FuelType" class="control-label"></label>
                <input asp-for="FuelType" class="form-control" />
                <span asp-validation-for="FuelType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/WebApplication1/Views/Cars/Index.cshtml
@model IEnumerable<CarRental.Models.Cars>

@{
    ViewData["Title"] = "Cars";
}

<h1>Cars</h1>

<p>
    <a asp-action="Create">Create New Car</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.An)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Firma)
            </th>
            
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.An)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Firma)
            </td>
            <td>
                <img src="@Url.Content(item.Imagine)" height="300px" width="500px">
               
            </td>
           
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>|
                <a asp-controller="Rents" asp-action="Create" >Rent</a>
            </td>
        </tr>
}
    </tbody>
</table>